## Copyright (C) 1996-2026 The Squid Software Foundation and contributors
##
## Squid software is distributed under GPLv2+ license and includes
## contributions from numerous individuals and organizations.
## Please see the COPYING and CONTRIBUTORS files for details.
##

cache_log /usr/local/squid/var/logs/performance-baseline/cache-kid${process_number}.log

coredump_dir /usr/local/squid/var/logs/performance-baseline/

workers 2

http_port 3128

http_access allow localhost

visible_hostname kid${process_number}.squid.test

cache_mem 0

logformat myFormat \
    %%sn=%sn \
    %%master_xaction=%master_xaction \
    %%transport::>connection_id=%transport::>connection_id \
    %%err_code=%err_code \
    %%err_detail=%err_detail \
    %%et_=%ts.%03tu \
    %%tr=%tr \
    %%dt=%dt \
    %%>A=%>A \
    %%>a=%>a \
    %%Ss=%Ss \
    %%>Hs=%>Hs \
    %%<Hs=%<Hs \
    %%<st=%<st \
    %%rm=%rm \
    %%ru=%ru \
    %%un=%[un \
    %%Sh=%Sh \
    %%<a=%<a \
    %%mt=%mt

access_log stdio:access-kid${process_number}.log myFormat

shutdown_lifetime 1 seconds
