name: Functionality Tests

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - run: node --version

    - run: echo ./boostrap.sh
    - run: echo ./configure
    - run: echo make
    - run: echo make check
    - run: echo make distcheck
    - run: ./test-suite/github-actions.sh ${{ github.event.pull_request.number }}


