# Tests in this workflow file are slower or more expensive than build tests in
# quick.yaml. These tests improve test coverage, but are unlikely to fail
# after quick.yaml tests succeed. Limiting these tests execution to staged
# commits optimizes CI responsiveness and costs while preserving decent
# quick.yaml problem detection probability.
#
# Anubis configuration must be kept in sync with the total number of
# tests executed for "auto" branch commits, including tests in other
# GitHub workflow file(s).

name: Staged commit

on:
  push:
    branches: [ "bag**", "auto", "SQUID-1171-ci-basic-perf-baseline-bag0" ]

  # allows to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel ongoing tests in case of push to staging branch,
  # but let previous bag** commit tests complete.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ contains(github.ref, 'refs/heads/auto')}}

jobs:

  performance-baseline:

    runs-on: ubuntu-24.04

    steps:
      # XXX: This step duplicates a functionality-tests step in quick.yaml
      - name: Install prerequisite Linux packages
        run: |
          # required for "apt-get build-dep" to work
          sudo sed --in-place -E 's/^(Types: deb)$/\1 deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get --quiet=2 update
          sudo apt-get --quiet=2 build-dep squid
          sudo apt-get --quiet=2 install libtool-bin valgrind

      # XXX: This step duplicates a functionality-tests step in quick.yaml
      - name: Setup a nodejs environment
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Checkout Squid sources
        uses: actions/checkout@v6

      - name: Test foreign exes
        run: |
          curl -o exes.tgz --no-progress-meter https://www.measurement-factory.com/extras/exes1.tgz
          tar -xvzf exes.tgz
          ./exes/client --version
          ./exes/server --version
          ./exes/squid --version
          sudo mkdir -p /usr/local/squid/sbin
          sudo mkdir -p /usr/local/squid/var/logs
          sudo mkdir -p /usr/local/squid/etc
          sudo cp -p ./exes/squid /usr/local/squid/sbin/
          sudo cp -p ./exes/mime.conf /usr/local/squid/etc/
          mkdir -p /usr/local/squid/sbin

      - run: ./test-suite/test-functionality.sh generic-performance

      # XXX: This step duplicates a functionality-tests step in quick.yaml
      # Squid logs are not readable to actions/upload-artifact below
      - name: Prep test logs
        if: success() || failure()
        run: sudo chmod -R a+rX /usr/local/squid

      # XXX: This step poorly duplicates a functionality-tests step in quick.yaml
      - name: Publish test logs
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: test-logs
          path: |
            "${{ runner.temp }}/*.log
            "${{ runner.temp }}/**/*.log
            /usr/local/squid/var/logs/overlord*/*.log
